"""update_barber_model

Revision ID: cd92ffce4aff
Revises: 37840448d4d0
Create Date: 2025-05-28 11:42:46.062351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cd92ffce4aff'
down_revision: Union[str, None] = '37840448d4d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', sa.DateTime(), nullable=False))
    op.alter_column('appointments', 'status',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('appointments', 'date')
    op.drop_column('appointments', 'time')
    op.drop_column('appointments', 'notes')
    op.add_column('services', sa.Column('barber_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'services', 'barbers', ['barber_id'], ['id'])
    op.drop_column('services', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'services', type_='foreignkey')
    op.drop_column('services', 'barber_id')
    op.add_column('appointments', sa.Column('notes', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.add_column('appointments', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.alter_column('appointments', 'status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("'pending'::character varying"))
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###
