"""sync_service_model


Revision ID: aa6d52716ca5
Revises: f2167e88aa67
Create Date: 2025-05-28 11:45:32.058919

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aa6d52716ca5'
down_revision: Union[str, None] = 'f2167e88aa67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('image', sa.String(length=255), nullable=False))
    op.drop_constraint(op.f('services_barber_id_fkey'), 'services', type_='foreignkey')
    op.drop_column('services', 'barber_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('barber_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('services_barber_id_fkey'), 'services', 'barbers', ['barber_id'], ['id'])
    op.drop_column('services', 'image')
    # ### end Alembic commands ###
